spring.application.name=teamservice

spring.datasource.url=jdbc:mysql://localhost:3305/team_db
spring.datasource.username=team-service-user
spring.datasource.password=team-service-password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
